### ISSUE TITLE
`fatrace: Failed to add watch for .: No such device` on ntfs mount, not on others

### ISSUE THREAD

**Issue by rbutoi** [martinpitt/fatrace#26]
On my ntfs-3g mounted external drive:

```
❯ sudo fatrace -c -t
fatrace: Failed to add watch for .: No such device
```

This works (great, I should add!) on ext4 drives -- any ideas here?

**Comment by martinpitt** [comment]
There's not much that fatrace can do if fanotify_mark() does not work on a particular file system. I would not expect this to ever work for FUSE file systems, as these are not under the kernel's control.

**Comment by rbutoi** [comment]
Thanks for the quick response and explanation!

**Comment by mrob27** [comment]
When this error happens (e.g. in kernel 5.17.5) it is avoidable. As "man fanotify_init" clearly indicates in the section for FAN_REPORT_FID,

> Note that the use of directory modification events are not supported when monitoring a mount point

The documentation does not explain why some mountpoints like /run/user/1234 work despite being "not supported".

Thus, the problem was introduced in the commit on Sep 30, 2019 commented _"Use FAN_REPORT_FID if available"_, and the fix is to not use FAN_REPORT_FID if the option_current_mount directory is in "a mount point".

In my case I care less about directory modification than the `-c` option. Therefore:

In `main()`, at the point when it is about to call `fanotify_init()`, I test `if (option_current_mount)` and use a `warnx()` to tell the user, _"When monitoring a mount_point, directory modification events\n  (CREATE, ATTRIB, MOVE, DELETE) cannot be reported."_ and then fallback to the code used when `FAN_REPORT_FID` is not defined.

This works on fuseblk filesystems which is good enough for me. If I want directory events I can run without the `-c` option and filter the output myself.

The "real" fix would be to attempt both `fanotify_init()` and the subsequent `fanotify_mark()`, detect the failure, and then fall back to the non-`FAN_REPORT_FID` code. I'm not sure if it needs to close the fan_fid from the first init attempt.
